<a href="https://colab.research.google.com/github/Abu-Taher01/PCA/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# !pip install numpy
import numpy as np
import pandas as pd

np.random.seed(23)

In [9]:
mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])

class1_sample=np.random.multivariate_normal(mu_vec1,cov_mat1,20)

df= pd.DataFrame(class1_sample, columns=['feature1','feature2','feature3'])

df['target'] = 1

mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])

class2_sample=np.random.multivariate_normal(mu_vec1,cov_mat1,20)

df1= pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])

df1['target'] = 0

df = pd.concat([df,df1],ignore_index=True)

df = df.sample(40)

In [10]:
df.head()

feature1  feature2  feature3  target
31 -0.200002  1.161269 -2.454170       0
16  1.705279  1.012474 -0.566929       1
23  0.595877 -1.063361  0.034654       0
7   0.301809  0.730070  0.041707       1
3   0.382700  0.874287  2.242790       1

In [13]:
import plotly.express as px

fig=px.scatter_3d(df, x='feature1',y='feature2',z='feature3',color=df['target'].astype('str'))

fig.update_traces(marker=dict(size=12,
                              line=dict(width=2,
                              color='DarkSlateGrey')),
                  selector=dict(mode='markers'))

fig.show()

In [16]:
# step 1 - Apply standard scaling

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df.iloc[:,0:3] = scaler.fit_transform(df.iloc[:,0:3])

In [18]:
#step 2 - Find Covarience Matrix
covariance_matrix = np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print('Covarience Matrix: \n', covariance_matrix)

Covarience Matrix: 
 [[ 1.02564103 -0.17908433  0.02317797]
 [-0.17908433  1.02564103  0.05479162]
 [ 0.02317797  0.05479162  1.02564103]]


In [20]:
#step 3 - Finding Eigen-values and Eigen-vectors
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

In [22]:
eigen_values

array([0.83084475, 1.2076048 , 1.03847353])